<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Core\Core.Persistence\Core.Persistence.csproj" />
    <ProjectReference Include="..\CourtOwners.Application\CourtOwners.Application.csproj" />
  </ItemGroup>

</Project>
