<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Ardalis.SmartEnum" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="MongoDB.Driver" />
		<PackageReference Include="Newtonsoft.Json" />
		<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
	</ItemGroup>

</Project>
