<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Ardalis.ApiEndpoints" />
		<PackageReference Include="Ardalis.ApiEndpoints.Swashbuckle" />
		<PackageReference Include="Asp.Versioning.Http" />
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="Swashbuckle.AspNetCore.Annotations" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Core.Shared\Core.Shared.csproj" />
	</ItemGroup>

</Project>
